version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-6.7.0}
    hostname: "{{.Node.Hostname}}-elasticsearch"
    environment:
      - discovery.zen.ping.unicast.hosts=elasticsearch
      - discovery.zen.minimum_master_nodes=1
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=false
      - xpack.license.self_generated.type=trial
      - cluster.name=es-cluster
      - node.name={{.Node.Hostname}}-elasticsearch
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    networks:
      - private
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    deploy:
      mode: 'global'
      endpoint_mode: dnsrr

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION:-6.7.0}
    networks:
      - private
      - public
    environment:
      - SERVER_NAME=kibana.${DOMAIN:-localhost}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_HOST:-http://elasticsearch}:${ELASTICSEARCH_PORT:-9200}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.frontend.rule=Host:kibana.${DOMAIN:-localhost}
        - traefik.enable=true
        - traefik.port=5601
        - traefik.tags=public
        - traefik.backend=kibana
        - traefik.docker.network=public
        - traefik.redirectorservice.frontend.entryPoints=http
        
  filebeat:
    image: docker.elastic.co/beats/filebeat:${ELASTIC_VERSION:-6.7.0}
    hostname: "{{.Node.Hostname}}-filebeat"
    user: root
    networks:
      - private
    configs:
      - source: fb_config
        target: /usr/share/filebeat/filebeat.yml
    volumes:
      - filebeat:/usr/share/filebeat/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
      - /var/log/:/var/log/:ro
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-elasticsearch}
      - KIBANA_HOST=${KIBANA_HOST:-kibana}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
      - ELASTICSEARCH_PORT=${ELASTICSEARCH_PORT:-9200}
      - KIBANA_PORT=${KIBANA_PORT:-5601}
    command: ["--strict.perms=false"]
    deploy:
      mode: global

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:${ELASTIC_VERSION:-6.7.0}
    hostname: "{{.Node.Hostname}}-metricbeat"
    user: root
    networks:
      - private
    configs:
      - source: mb_config
        target: /usr/share/metricbeat/metricbeat.yml
    volumes:
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - metricbeat:/usr/share/metricbeat/data
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-elasticsearch}
      - KIBANA_HOST=${KIBANA_HOST:-kibana}
      - KIBANA_PORT=${KIBANA_PORT:-5601}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
    deploy:
      mode: global

networks:
  private:
    driver: overlay
    name: private
  public:
    external: true

volumes:
  filebeat: {}
  metricbeat: {}
  elasticsearch: {}

configs:
  fb_config:
    file: $PWD/filebeat/config/filebeat.yml
  mb_config:
    file: $PWD/metricbeat/config/metricbeat.yml
