version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-6.5.0}
    hostname: "{{.Node.Hostname}}-elasticsearch"
    environment:
      - discovery.zen.ping.unicast.hosts=elasticsearch
      - discovery.zen.minimum_master_nodes=1
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=false
      - xpack.license.self_generated.type=trial
      - cluster.name=es-cluster
      - node.name={{.Node.Hostname}}-elasticsearch
      - network.host=0.0.0.0
    networks:
      - appnet
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    deploy:
      mode: 'global'
      endpoint_mode: dnsrr

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION:-6.5.0}
    networks:
      - appnet
      - public
    environment:
      - SERVER_NAME=https://kibana.${DOMAIN}
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOST:-elasticsearch}:${ELASTICSEARCH_PORT:-9200}
      - XPACK_MONITORING_ENABLED=false
      - ELASTICSEARCH_URL=${ELASTICSEARCH_HOST:-elasticsearch}:${ELASTICSEARCH_PORT:-5601}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-changeme}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.backend.loadbalancer.sticky=false"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.backend=kibana"
        - "traefik.docker.network=appnet"
        - "traefik.entrypoints=https"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.rule=Host:kibana.${DOMAIN}"
        - "traefik.port=5601"
        
  filebeat:
    image: docker.elastic.co/beats/filebeat:${ELASTIC_VERSION:-6.5.0}
    hostname: "{{.Node.Hostname}}-filebeat"
    user: root
    networks:
      - appnet
    configs:
      - source: fb_config
        target: /usr/share/filebeat/filebeat.yml
    volumes:
      - filebeat:/usr/share/filebeat/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
      - /var/log/:/var/log/:ro
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-elasticsearch}
      - KIBANA_HOST=${KIBANA_HOST:-kibana}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-changeme}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
      - ELASTICSEARCH_PORT=${ELASTICSEARCH_PORT:-9200}
      - KIBANA_PORT=${KIBANA_PORT:-5601}
    command: ["--strict.perms=false"]
    deploy:
      mode: global

networks:
  appnet:
    external: true
  public:
    external: true

volumes:
  filebeat: {}
  elasticsearch: {}

configs:
  fb_config:
    file: $PWD/filebeat/config/filebeat.yml
